#!/bin/bash
echo "compiling main2.cpp..."
g++ -c main.cpp bicycle_machine.cpp
echo "linking all..."
g++ -o ProjectX main.o bicycle_machine.o -g -pthread -lsfml-system -lsfml-window -lsfml-graphics -lX11 -std=c++17
#echo "start ProjectX..."
#gdb ./ProjectX
