#!/bin/bash
echo "compiling main2.cpp..."
g++ -c main.cpp
echo "linking all..."
g++ -o ProjectX main.o -pthread -lsfml-system -lsfml-window -lsfml-graphics -lX11 -std=c++17
#echo "start ProjectX..."
#./ProjectX
